name: Weekly DSRS KB Refresh

on:
  schedule:
    # Runs at 14:00 UTC every Monday (09:00 AM America/Chicago during CDT)
    - cron: '0 14 * * 1'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir requests beautifulsoup4 pandas

      - name: Run DSRS KB refresh
        run: |
          python refresh_dsrs_kb.py

      - name: Commit and push updated CSVs/DB
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dsrs_*.csv dsrs_kb.db
          git commit -m "Weekly KB refresh: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
